[package]
name = "formula-xls"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.32"
cfb = "0.10"
encoding_rs = "0.8"
formula-format = { path = "../formula-format" }
formula-model = { path = "../formula-model" }
log = "0.4"
thiserror = "2.0"

[dev-dependencies]
tempfile = "3.10"
