[package]
name = "xlsb-diff"
version = "0.1.0"
edition = "2021"

[dependencies]
xlsx-diff = { path = "../xlsx-diff" }

[dev-dependencies]
anyhow = "1.0"
ms-offcrypto-writer = "1"
rand = "0.9"
tempfile = "3.10"
