[package]
name = "formula-xlsx"
version = "0.1.0"
edition = "2021"

[dependencies]
formula-model = { path = "../formula-model" }
formula-vba = { path = "../formula-vba" }
quick-xml = "0.37"
roxmltree = "0.20"
thiserror = "1"
zip = { version = "2.1", default-features = false, features = ["deflate"] }

[dev-dependencies]
base64 = "0.22"
cfb = "0.10"
pretty_assertions = "1"
insta = "1.46"
rust_xlsxwriter = "0.64"
tempfile = "3.10"
